### ISSUE TITLE
Crear funcion para Crawler, Scraping y Parsing

### ISSUE THREAD

**Issue by 3rickDJ** [3rickDJ/RI-K-means#1]
Realizar Crawling a n niveles, realizando Scraping y parsing. 
Con ello generar el corpus de documentos.

Generar el diccionario de términos de todo el corpus (Generar un documento de texto donde se guarde el diccionario)

**Comment by DiwsgenLop** [comment]
![Image](https://github.com/3rickDJ/RI-K-means/assets/131631133/6b2b1778-6d83-4cfb-8b80-a930f4c55b55)

Error en algunas paginas NonType, de otros si los scrapea y los guarda en el corpus


![Image](https://github.com/3rickDJ/RI-K-means/assets/131631133/d71d5661-d11e-4557-8fe1-ca360bf93ac9)

En una sola linea
